version: '3.8'

services:
  # PHP Service
  php:
    build:
      dockerfile: Php.DockerFile
    container_name: laravel_php
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - mysql

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php
    networks:
      - laravel_network

  # Redis Service
  redis:
    image: redis:latest
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
