version: '3.8'

services:
  # PHP Service
  php:
    build:
      dockerfile: Php.DockerFile
    container_name: laravel_php
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel_network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  # Redis Service
  redis:
    image: redis:latest
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
